CREATE TABLE IF NOT EXISTS labschedules (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ROOM_NUMBER VARCHAR(10) NOT NULL,
    DAY_GROUP VARCHAR(20) NOT NULL,
    TIME_SLOT VARCHAR(50) NOT NULL,
    STATUS ENUM('Available', 'Reserved', 'Maintenance') DEFAULT 'Available',
    NOTES TEXT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
); 