CREATE TABLE IF NOT EXISTS reservations (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    IDNO INT(11) NOT NULL,
    LABORATORY VARCHAR(50) NOT NULL,
    PC_NUMBER INT NOT NULL,
    DATE DATE NOT NULL,
    TIME_SLOT VARCHAR(20) NOT NULL,
    PURPOSE TEXT NOT NULL,
    STATUS ENUM('pending', 'confirmed', 'cancelled') NOT NULL DEFAULT 'pending',
    CREATED_AT DATETIME NOT NULL,
    UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (IDNO) REFERENCES user(IDNO) ON DELETE CASCADE
);